wifi_ssid01: "ssid01"
wifi_password01: "pwd01"
wifi_ssid02: "faloaip"
wifi_password02: "pwd02"
wifi_ssid03: "ssid03"
wifi_password03: "pwd03"
combisensor_ota_password: ""
combisensor_wifi_ap_password: ""
combisensor_api_key: ""