substitutions:
  sub_name: "kombisensor-5954e8"
  sub_fname: "kombisensor-5954e8"
  # Feather S3 TFT
  #sub_sda: GPIO42
  #sub_scl: GPIO41
  # QT PY S3 PSRAM
  sub_sda: GPIO07
  sub_scl: GPIO06

esphome:
  #name: kombisensor
  name: "${sub_name}"
  #friendly_name: "Kombisensor"
  friendly_name: "${sub_fname}"
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  encryption:
    key: !secret combisensor_api_key

ota:
  - platform: esphome
    password: !secret combisensor_ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid01
    password: !secret wifi_password01
  - ssid: !secret wifi_ssid02
    password: !secret wifi_password02
  - ssid: !secret wifi_ssid03
    password: !secret wifi_password03

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Combisensor-Xx Fallback Hotspot"
    password: !secret combisensor_wifi_ap_password

captive_portal:

web_server:
  port: 80

uart:
  rx_pin: GPIO05
  tx_pin: GPIO16
  baud_rate: 9600

i2c:
  sda: ${sub_sda}
  scl: ${sub_scl}
  id: i2c0

sensor:
  - platform: sds011
    update_interval: 5min
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"

  - platform: bmp280_i2c
    i2c_id: i2c0
    temperature:
      name: "Outside Temperature"
      oversampling: 16x
    pressure:
      name: "Outside Pressure"
    address: 0x76
    update_interval: 5min

button:
  - platform: restart
    name: "Restart"
