esphome:
  name: kombisensor-init
  friendly_name: kombisensor_init
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret raumsenor_api_key

ota:
  - platform: esphome
    password: !secret raumsenor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kombisensor-Init"
    password: !secret raumsenor_ap_password

captive_portal: